# Generated by Django 5.1.3 on 2024-11-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_maincategory_id_alter_subcategory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'managed': False},
        ),
    ]
