# Generated by Django 5.1.3 on 2024-11-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_maincategory_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maincategory',
            table='main_category',
        ),
    ]
