# Generated by Django 5.1.3 on 2024-11-14 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_maincategory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={},
        ),
    ]
