# Generated by Django 5.1.3 on 2024-11-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_maincategory_id_alter_maincategory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
