# Generated by Django 5.1.3 on 2024-12-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_subcategory_id_alter_subcategory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'aspects',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('energy_efficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('power_consumption', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='chatbot.subcategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('review_score', models.IntegerField(blank=True, null=True)),
                ('syllable_count', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('general_polarity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='chatbot.product')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_text', models.TextField(blank=True, null=True)),
                ('sentiment_word_count', models.IntegerField(blank=True, null=True)),
                ('sentiment_polarity', models.IntegerField(blank=True, null=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_aspects', to='chatbot.aspect')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_aspects', to='chatbot.review')),
            ],
            options={
                'db_table': 'review_aspects',
            },
        ),
    ]
